# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ec77d899e1cdcabb9e92a378c2ac18fd291ab9d03c9035e8deb93be0bbe4c1152ccdd53b3aaa43212eed0224b65134ed75cc107029d90f608d105d977e2e700

test:
  secret_key_base: f0e396c3010f6f95a9329d2a8f008fd830296c7f58857c3bfee2eafef625030231fa7339ae08e70760dc5a0f8eac5f49186892b1f53cc0a15050b22e1ea32f09

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
